In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
paths = { 
    2022: [
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2022\month=01\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2022\month=06\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2022\month=12\data.parquet",
    ],
    2023: [
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2023\month=01\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2023\month=06\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2023\month=12\data.parquet",
    ],
    2024: [
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2024\month=01\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2024\month=06\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2024\month=12\data.parquet",
    ],
    2025: [
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2025\month=01\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2025\month=06\data.parquet",
        r"D:\Projeto_Supervisionado\taxi-chicago-analysis\data\raw\taxi_trips\year=2025\month=12\data.parquet",
    ]
}

dfs_por_ano = {}

for ano, arquivos in paths.items():
    dfs = [pd.read_parquet(p) for p in arquivos]
    dfs_por_ano[ano] = pd.concat(dfs, ignore_index=True)

In [8]:
dfs_por_ano[2022].head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,...,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_community_area,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,pickup_census_tract,dropoff_census_tract
0,54d812a0b88f8f9707825261014b3563a0a60ace,f98ae5e71fdda8806710af321dce58002146886c013f41...,2022-01-01,2022-01-01 00:00:00,536,4.83,14.75,0,0,0,...,22,41.922761,-87.699155,"{'coordinates': [-87.6991553432, 41.9227606205...",28,41.874005,-87.663518,"{'coordinates': [-87.6635175498, 41.874005383]...",None,None
1,7125b9e03a0f16c2dfb5eaf73ed057dc51eb68ef,8eca35a570101ad24c638f1f43eecce9d0cb7843e13a75...,2022-01-01,2022-01-01 00:15:00,897,2.07,9.75,0,0,1.5,...,32,41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",8,41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",None,None
2,f1a650ee419b4e52d766432e6f86eca3457bfb37,e2d8418fcdb061eee0a4318fba0a6a1200aaff0143feb0...,2022-01-01,2022-01-01 00:30:00,2200,2.48,9.36,2.14,0,0,...,32,41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",8,41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",None,None
3,058322b4ecd94483ab01630b6a07da6221fbac7f,c9867d006415cbc16529555f98cdeb44cb53aeaf1d9ae7...,2022-01-01,2022-01-01 00:00:00,0,0,3.25,0,0,0,...,33,41.857184,-87.620335,"{'coordinates': [-87.6203346241, 41.8571838585...",33,41.857184,-87.620335,"{'coordinates': [-87.6203346241, 41.8571838585...",None,None
4,0f0c856e620e6b4dfd2bb1e921d966dd179eeca1,b21050ab3ad3d0972fd6378f6bf4d0251a8a7af42e6e0e...,2022-01-01,2022-01-01 00:00:00,33,0.17,63.27,0,0,0,...,3,41.965812,-87.655879,"{'coordinates': [-87.6558787862, 41.96581197],...",3,41.965812,-87.655879,"{'coordinates': [-87.6558787862, 41.96581197],...",None,None

In [9]:
dfs_por_ano[2023].head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,...,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
0,0fca59218b11688279d795c03c4d16f851f13fa0,e2c349c7cbb608d552aa0b5814031943f13641ef9e50d8...,2023-01-01,2023-01-01 00:15:00,1037,4.82,6,32,15.75,3.25,...,Credit Card,Taxicab Insurance Agency Llc,41.944227,-87.655998,"{'coordinates': [-87.6559981815, 41.9442266014...",41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",None,None
1,1e539d6e7501164c6b76b761c3152c235e206d59,4ab7a7510c1ebcc9b2e3eaa7bdd6508dbea34da7986aca...,2023-01-01,2023-01-01 00:15:00,1341,16.63,76,8,41.5,5,...,Credit Card,Sun Taxi,41.980264,-87.913625,"{'coordinates': [-87.913624596, 41.9802643146]...",41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",None,None
2,2b3c5200439d51f626b60380809bbbcca766a85b,8c76eb82f069c0731a0049cb78898f02cc5ac6990244c9...,2023-01-01,2023-01-01 00:15:00,844,3.84,24,8,16.14,4.03,...,Mobile,Sun Taxi,41.901207,-87.676356,"{'coordinates': [-87.6763559892, 41.9012069941...",41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",None,None
3,45b2ea39cfff64d61a46ef016e16f8ee74e9ed23,a688de71e9eb70603ba839dc7faf949968ae3e971e0575...,2023-01-01,2023-01-01 00:00:00,361,0.63,32,32,5.5,0,...,Cash,5 Star Taxi,41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",None,None
4,464df6aaaf97ca8745985c2a5b2e481067a2bfb6,8b1a88e5a09cfd55ca72d267f00f56fa50a42aa322bdfe...,2023-01-01,2023-01-01 00:15:00,704,0.99,14,14,7.75,0,...,Cash,Flash Cab,41.968069,-87.721559,"{'coordinates': [-87.7215590627, 41.968069], '...",41.968069,-87.721559,"{'coordinates': [-87.7215590627, 41.968069], '...",None,None

In [ ]:
dfs_por_ano[2024].head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,...,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
0,001b45fb611d0a720696a47b3460731cf3ebe6f9,1b7aef0344f45914e7942efad05553934fe222c880a1cb...,2024-01-01,2024-01-01 00:00:00,856,11,76,21,28.5,3.4,...,Mobile,Globe Taxi,41.980264,-87.913625,"{'coordinates': [-87.913624596, 41.9802643146]...",41.938666,-87.711211,"{'coordinates': [-87.7112105933, 41.9386661962...",None,None
1,033a57e39e82145683090b93f7f660d9623e28b8,511d5a90fddd5d591ca80c1c2969c190f8ad2997c0b6e9...,2024-01-01,2024-01-01 00:15:00,1587,10.93,70,28,29.5,0,...,Prcard,5 Star Taxi,41.745758,-87.708366,"{'coordinates': [-87.7083657043, 41.7457577128...",41.874005,-87.663518,"{'coordinates': [-87.6635175498, 41.874005383]...",None,None
2,054bbff2c120ec8b40dbe90b6b15cf52847d46fd,6c1e4e8e25a1b47575b359c5a0844cf23c50e540a86ecd...,2024-01-01,2024-01-01 00:00:00,392,1.03,8,7,6.25,0,...,Cash,Flash Cab,41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",41.922686,-87.649489,"{'coordinates': [-87.6494887289, 41.9226862843...",None,None
3,0b8d881ee35db48343db0f2a526a040f9ab0f520,07009b8e9b32f36656567f7809b970af38e59dbb58704a...,2024-01-01,2024-01-01 00:15:00,1038,9.73,43,32,25.52,0,...,Mobile,Flash Cab,41.761578,-87.572782,"{'coordinates': [-87.5727819867, 41.7615779081...",41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",None,None
4,11230d9cfd992d84a23d9efde09f76a193758d26,d12b9e3cb8201f4c58e7d3ad3a970bb83f46788415f5d9...,2024-01-01,2024-01-01 00:00:00,177,0.14,28,28,20.45,5.01,...,Mobile,Medallion Leasin,41.874005,-87.663518,"{'coordinates': [-87.6635175498, 41.874005383]...",41.874005,-87.663518,"{'coordinates': [-87.6635175498, 41.874005383]...",None,None

In [11]:
dfs_por_ano[2025].head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,...,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
0,53fc5da5892235cce7b470dc94440e491eae9532,9ac243b4bb4548e7214a248a491aa3ddddf391820e6c7b...,2025-01-01,2025-01-01 00:45:00,2886,18.28,76,32,51.5,5.6,...,Mobile,Medallion Leasin,41.980264,-87.913625,"{'coordinates': [-87.913624596, 41.9802643146]...",41.878866,-87.625192,"{'coordinates': [-87.6251921424, 41.8788655841...",None,None
1,0275e2d8147a31e1ce320c5fb15f9910563cafe1,84957c8960b674346784746bbc1d48cafff4976b162323...,2025-01-01,2025-01-01 00:15:00,758,2.93,8,8,9.75,0,...,Prcard,Flash Cab,41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",None,None
2,060f692c4ca69e552c07a97c99715ad51112470e,e533bfdc483206f9c02c1c879a118d88f0a3ca1cd2703f...,2025-01-01,2025-01-01 00:00:00,6,0,6,6,30,0,...,Credit Card,Flash Cab,41.944227,-87.655998,"{'coordinates': [-87.6559981815, 41.9442266014...",41.944227,-87.655998,"{'coordinates': [-87.6559981815, 41.9442266014...",None,None
3,05aa05bf6f3ec476715fad9f706bd137e08e00b7,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2025-01-01,2025-01-01 00:15:00,1233,13.66,76,6,35,8.1,...,Credit Card,Globe Taxi,41.980264,-87.913625,"{'coordinates': [-87.913624596, 41.9802643146]...",41.944227,-87.655998,"{'coordinates': [-87.6559981815, 41.9442266014...",None,None
4,0b2d1368456148b049af41dc8aa565d688081756,2d5029b701200a2ab66bd5071f743efe20a3036597d2b3...,2025-01-01,2025-01-01 00:00:00,11,0,77,77,20,5.12,...,Credit Card,Sun Taxi,41.986712,-87.663416,"{'coordinates': [-87.6634164054, 41.9867117999...",41.986712,-87.663416,"{'coordinates': [-87.6634164054, 41.9867117999...",None,None

In [13]:
dfs_por_ano[2022].describe()

,trip_start_timestamp,trip_end_timestamp,dropoff_centroid_latitude,dropoff_centroid_longitude,pickup_centroid_latitude,pickup_centroid_longitude
count,1266234,1266234,1.266234e+06,1.266234e+06,1.266234e+06,1.266234e+06
mean,2022-07-20 01:32:36.672700,2022-07-20 01:51:08.520983,4.189407e+01,-8.766141e+01,4.189705e+01,-8.767771e+01
min,2022-01-01 00:00:00,2022-01-01 00:00:00,4.166014e+01,-8.791362e+01,4.165192e+01,-8.791362e+01
25%,2022-06-03 16:30:00,2022-06-03 16:45:00,4.187887e+01,-8.766352e+01,4.187887e+01,-8.766352e+01
50%,2022-06-20 22:30:00,2022-06-20 22:45:00,4.189251e+01,-8.763331e+01,4.189251e+01,-8.763331e+01
75%,2022-12-09 11:15:00,2022-12-09 11:30:00,4.192269e+01,-8.762519e+01,4.193867e+01,-8.762519e+01
max,2022-12-31 23:45:00,2023-01-01 15:00:00,4.202122e+01,-8.753490e+01,4.201605e+01,-8.753490e+01
std,NaN,NaN,5.724402e-02,7.138684e-02,5.885943e-02,9.520996e-02

In [ ]:
print('-' * 30, "SHAPE DOS DADOS", '-' * 30)
print("Ano 2022: ", dfs_por_ano[2022].shape)
print("Ano 2023: ", dfs_por_ano[2023].shape)
print("Ano 2024: ", dfs_por_ano[2024].shape)
print("Ano 2025: ", dfs_por_ano[2025].shape)

------------------------------ SHAPE DOS DADOS ------------------------------
Ano 2022:  (1266234, 23)
Ano 2023:  (1351096, 23)
Ano 2024:  (1391794, 23)
Ano 2025:  (1478254, 23)

In [23]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print('-' * 30, "Dados Nulos", '-' * 30)
for ano, df in dfs_por_ano.items():
    nulos = df.isnull().sum()
    nulos = nulos[nulos > 0]

    perc = (nulos / len(df)) * 100

    print(f"\nAno {ano}")
    
    if nulos.empty:
        print("Sem valores nulos 🎉")
    else:
        print(pd.DataFrame({
            "nulos": nulos,
            "%": perc.round(2)
        }).sort_values("nulos", ascending=False))

------------------------------ Dados Nulos ------------------------------

Ano 2022
                         nulos      %
pickup_census_tract     719928  56.86
dropoff_census_tract    719928  56.86
dropoff_community_area    6344   0.50
trip_total                 698   0.06
extras                     698   0.06
fare                       698   0.06
tips                       698   0.06
tolls                      698   0.06
pickup_community_area      485   0.04
trip_seconds               200   0.02
trip_miles                  18   0.00

Ano 2023
                         nulos      %
pickup_census_tract     737815  54.61
dropoff_census_tract    737815  54.61
dropoff_community_area    7417   0.55
tolls                     2275   0.17
tips                      2275   0.17
trip_total                2275   0.17
fare                      2275   0.17
extras                    2275   0.17
pickup_community_area      405   0.03
trip_seconds               195   0.01
trip_miles                   2   0.00

Ano 2024
                         nulos      %
pickup_census_tract     758271  54.48
dropoff_census_tract    758271  54.48
dropoff_community_area    8419   0.60
tolls                     3625   0.26
tips                      3625   0.26
trip_total                3625   0.26
fare                      3625   0.26
extras                    3625   0.26
pickup_community_area      687   0.05
trip_seconds               229   0.02
trip_miles                  18   0.00

Ano 2025
                         nulos      %
pickup_census_tract     790381  53.47
dropoff_census_tract    790381  53.47
dropoff_community_area    7437   0.50
tolls                     2288   0.15
tips                      2288   0.15
trip_total                2288   0.15
fare                      2288   0.15
extras                    2288   0.15
pickup_community_area      766   0.05
trip_seconds               207   0.01
trip_miles                   8   0.00

In [25]:
print('-' * 30, "Coordenadas Inválidas", '-' * 30)

for ano, df in dfs_por_ano.items():
    invalid = df[
        (df['pickup_centroid_latitude'] < 41.6) | (df['pickup_centroid_latitude'] > 42.1) |
        (df['pickup_centroid_longitude'] < -87.9) | (df['pickup_centroid_longitude'] > -87.5)
    ]
    
    print(f"Ano {ano}: {len(invalid)} registros inválidos")

------------------------------ Coordenadas Inválidas ------------------------------
Ano 2022: 164767 registros inválidos
Ano 2023: 223477 registros inválidos
Ano 2024: 248033 registros inválidos
Ano 2025: 231812 registros inválidos

In [29]:
print('-' * 30, "Outliers", '-' * 30)


for ano, df in dfs_por_ano.items():
    df['trip_miles'] = pd.to_numeric(df['trip_miles'], errors='coerce')
    df['trip_seconds'] = pd.to_numeric(df['trip_seconds'], errors='coerce')
    df['fare'] = pd.to_numeric(df['fare'], errors='coerce')

    outliers = df[
        (df['trip_miles'] < 0) | (df['trip_miles'] >= 100) |
        (df['trip_seconds'] < 60) | (df['trip_seconds'] > 7200) |
        (df['fare'] < 2.5) | (df['fare'] > 500)
    ]

    print(f"Ano {ano}: {len(outliers)} outliers")

------------------------------ Outliers ------------------------------
Ano 2022: 66694 outliers
Ano 2023: 67203 outliers
Ano 2024: 81596 outliers
Ano 2025: 83470 outliers

In [31]:
print('-' * 30, "Duplicatas por trip_id", '-' * 30)

for ano, df in dfs_por_ano.items():
    dup_rows = df[df['trip_id'].duplicated(keep=False)]
    print(f"Ano {ano}: {len(dup_rows)} linhas duplicadas")

------------------------------ Duplicatas por trip_id ------------------------------
Ano 2022: 0 linhas duplicadas
Ano 2023: 0 linhas duplicadas
Ano 2024: 0 linhas duplicadas
Ano 2025: 0 linhas duplicadas

In [32]:
print('-' * 30, "Inconsistência Temporal", '-' * 30)

for ano, df in dfs_por_ano.items():
    df['trip_start_timestamp'] = pd.to_datetime(df['trip_start_timestamp'])
    df['trip_end_timestamp'] = pd.to_datetime(df['trip_end_timestamp'])

    invalid_time = df[df['trip_end_timestamp'] < df['trip_start_timestamp']]
    
    print(f"Ano {ano}: {len(invalid_time)} inconsistências")

------------------------------ Inconsistência Temporal ------------------------------
Ano 2022: 9 inconsistências
Ano 2023: 4 inconsistências
Ano 2024: 3 inconsistências
Ano 2025: 1 inconsistências

In [33]:
print('-' * 30, "Resumo Percentual", '-' * 30)

for ano, df in dfs_por_ano.items():
    total = len(df)

    outliers = df[
        (df['trip_miles'] < 0) | (df['trip_miles'] >= 100) |
        (df['trip_seconds'] < 60) | (df['trip_seconds'] > 7200) |
        (df['fare'] < 2.5) | (df['fare'] > 500)
    ]

    perc = (len(outliers) / total) * 100

    print(f"Ano {ano}: {perc:.2f}% outliers")

------------------------------ Resumo Percentual ------------------------------
Ano 2022: 5.27% outliers
Ano 2023: 4.97% outliers
Ano 2024: 5.86% outliers
Ano 2025: 5.65% outliers